# TASK-1

# Titanic Classification :
### Problem statement:-Make a system which tells whether the person will be save from sinking. What factors were most likely lead to success-socio-economic status, age, gender and more.

# Data Set Column Descriptions
* passengerID:-passenger id no
* pclass: Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)
* survived: Survival (0 = No; 1 = Yes)
* name: Name
* sex: Sex
* age: Age
* sibsp: Number of siblings/spouses aboard
* ticket:Ticket no
* fare: Passenger fare (British pound)
* cabin:
* embarked: Port of embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)

# 1. Load the Data and Analysis of Variables

In [2]:
#Importing Important Libraries
import pandas as pd

In [3]:
#Reading CSV File
df = pd.read_csv("/content/archive (6).zip")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

# 2.Rename unwanted columns to make their use easier

In [5]:
#Removing unwanted Column's
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [6]:
#Defining Dependent and Independent Variable
X = df.drop(["Survived"],axis="columns")
y = df.Survived

In [7]:
#Get Dummy Values for Sex column
dummies = pd.get_dummies(X.Sex)
dummies.head()

   female  male
0       0     1
1       1     0
2       0     1
3       0     1
4       1     0

In [8]:
#Adding Dummies Column to the Dataframe
X = pd.concat([X,dummies],axis="columns")
X

     Pclass     Sex   Age      Fare  female  male
0         3    male  34.5    7.8292       0     1
1         3  female  47.0    7.0000       1     0
2         2    male  62.0    9.6875       0     1
3         3    male  27.0    8.6625       0     1
4         3  female  22.0   12.2875       1     0
..      ...     ...   ...       ...     ...   ...
413       3    male   NaN    8.0500       0     1
414       1  female  39.0  108.9000       1     0
415       3    male  38.5    7.2500       0     1
416       3    male   NaN    8.0500       0     1
417       3    male   NaN   22.3583       0     1

[418 rows x 6 columns]

In [9]:
#Dropping Sex Column after getting Dummies Value for Male and Female
X.drop(["Sex"],axis="columns",inplace=True)
X.head()

   Pclass   Age     Fare  female  male
0       3  34.5   7.8292       0     1
1       3  47.0   7.0000       1     0
2       2  62.0   9.6875       0     1
3       3  27.0   8.6625       0     1
4       3  22.0  12.2875       1     0

# 3.check null values

In [10]:
#Looking for Null Values in DataFrame
X.isna().sum()

Pclass     0
Age       86
Fare       1
female     0
male       0
dtype: int64

In [11]:
#Replacing Null Values with Mean of Age
X.Age = X.Age.fillna(X.Age.mean())
X.head()

   Pclass   Age     Fare  female  male
0       3  34.5   7.8292       0     1
1       3  47.0   7.0000       1     0
2       2  62.0   9.6875       0     1
3       3  27.0   8.6625       0     1
4       3  22.0  12.2875       1     0

In [12]:
#Verifying that all Null Values are Gone
X.isna().sum()

Pclass    0
Age       0
Fare      1
female    0
male      0
dtype: int64

# 4.Split test and train data set

In [13]:
#Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

# 5. Create model

In [14]:
#Creating Naive Bayes Model
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [16]:
#Fitting the Model with Data
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.naive_bayes import GaussianNB

# Create an Imputer transformer
imputer = SimpleImputer(strategy='mean')  # You can also try 'median' or 'most_frequent' depending on your data

# Create a pipeline with the Imputer and the GaussianNB classifier
pipeline = make_pipeline(imputer, GaussianNB())

# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('gaussiannb', GaussianNB())])

In [23]:
#Score of the Model
accuracy = pipeline.score(X_test, y_test)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [28]:
#Predicting the Data of First 10 Passengers
predictions = pipeline.predict(X[:10])

print(predictions)

[0 1 0 0 1 0 1 0 1 0]